In [1]:
import numpy as np
import tensorflow as tf

2021-11-04 13:54:48.281934: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-11-04 13:54:48.281978: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
# Neural Network
# Low level construction

# Define inputs (features)
inputs = tf.constant([[1.0, 35.0]])

# Define weights
weights = tf.Variable([[-0.05], [-0.01]])

# Define the bias
bias = tf.Variable([0.05])

# Multiply inputs (features) by the weights
product = tf.matmul(inputs, weights)

# Define dense layer
dense = tf.keras.activations.sigmoid(product + bias)

2021-11-04 13:54:49.631694: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-11-04 13:54:49.631732: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-11-04 13:54:49.631749: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-FC4EGDV): /proc/driver/nvidia/version does not exist
2021-11-04 13:54:49.631974: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
# Neural Network
# High level construction

data = tf.ones([2, 2])  # esto consigue que compile, pero tendría que cambiar

# Define input (features)
inputs = tf.constant(data, tf.float32)

# Define first dense layer
dense1 = tf.keras.layers.Dense(10, activation='sigmoid')(inputs)

# Define second dense layer
dense2 = tf.keras.layers.Dense(5, activation='sigmoid')(dense1)

# Define output (predictions) layer
outputs = tf.keras.layers.Dense(1, activation='sigmoid')(dense2)

In [4]:
# Low level

borrower_features = np.array([[ 2.,  2., 43.]], dtype=np.float32)

# Initialize bias1
bias1 = tf.Variable(1.0, dtype=tf.float32)

# Initialize weights1 as 3x2 variable of ones
weights1 = tf.Variable(np.ones([3,2]), dtype=tf.float32)

# Perform matrix multiplication
product1 = tf.matmul(borrower_features, weights1)

# Apply sigmoid activation function to product1 + bias1
dense1 = tf.keras.activations.sigmoid(product1 + bias1)

# Initialize bias2 and weights2
bias2 = tf.Variable(1.0, dtype=tf.float32)
weights2 = tf.Variable(np.ones([2, 1]), dtype=tf.float32)

# Perform matrix multiplication
product2 = tf.matmul(dense1, weights2)

# Apply activation to product2 + bias2 and print the prediction
prediction = tf.keras.activations.sigmoid(product2 + bias2)

print(f"prediction {prediction.numpy()}")
print("actual 1")

prediction [[0.95257413]]
actual 1


In [5]:
borrower_features = np.array([[ 3.,  3., 23.],
       [ 2.,  1., 24.],
       [ 1.,  1., 49.],
       [ 1.,  1., 49.],
       [ 2.,  1., 29.]], dtype=np.float32)

weights1 = tf.Variable(
  np.array([[-0.6 ,  0.6 ],
       [ 0.8 , -0.3 ],
       [-0.09, -0.08]]), dtype=tf.float32)

# Compute the product of borrower_features and weights1
products1 = tf.matmul(borrower_features, weights1)

# Apply a sigmoid activation function to products1 + bias1
dense1 = tf.keras.activations.sigmoid(products1 + bias1)

# Print the shapes of borrower_features, weights1, bias1, and dense1
print(f"{borrower_features.shape=}")
print(f"{weights1.shape=}")
print(f"{bias1.shape=}")
print(f"{dense1.shape=}")

borrower_features.shape=(5, 3)
weights1.shape=TensorShape([3, 2])
bias1.shape=TensorShape([])
dense1.shape=TensorShape([5, 2])


In [6]:
# High level

# Data
borrower_features = np.array([[0.6964692 , 0.28613934, 0.22685145, 0.5513148 , 0.71946895,
        0.42310646, 0.9807642 , 0.6848297 , 0.4809319 , 0.39211753],
       [0.343178  , 0.7290497 , 0.43857226, 0.0596779 , 0.39804426,
        0.7379954 , 0.18249173, 0.17545176, 0.53155136, 0.53182757],
       [0.63440096, 0.8494318 , 0.7244553 , 0.6110235 , 0.7224434 ,
        0.32295892, 0.36178866, 0.22826323, 0.29371405, 0.63097614],
       [0.09210494, 0.4337012 , 0.43086275, 0.4936851 , 0.4258303 ,
        0.31226122, 0.4263513 , 0.89338917, 0.94416004, 0.50183666],
       [0.6239529 , 0.11561839, 0.31728548, 0.4148262 , 0.86630917,
        0.25045538, 0.48303425, 0.98555976, 0.5194851 , 0.61289454],
       [0.12062866, 0.8263408 , 0.6030601 , 0.545068  , 0.34276384,
        0.30412078, 0.4170222 , 0.68130076, 0.87545687, 0.51042235],
       [0.6693138 , 0.58593655, 0.6249035 , 0.67468905, 0.84234244,
        0.08319499, 0.76368284, 0.24366638, 0.19422296, 0.57245696],
       [0.09571252, 0.8853268 , 0.62724894, 0.7234163 , 0.01612921,
        0.5944319 , 0.55678517, 0.15895964, 0.15307051, 0.6955295 ],
       [0.31876642, 0.6919703 , 0.5543833 , 0.3889506 , 0.9251325 ,
        0.84167   , 0.35739756, 0.04359146, 0.3047681 , 0.39818567],
       [0.70495886, 0.99535847, 0.35591486, 0.7625478 , 0.5931769 ,
        0.69170177, 0.15112746, 0.39887628, 0.2408559 , 0.343456  ]],
      dtype=np.float32)

# Define first dense layer
dense1 = tf.keras.layers.Dense(7, activation='sigmoid')(borrower_features)

# Define a dense layer with 3 output nodes
dense2 = tf.keras.layers.Dense(3, activation='sigmoid')(dense1)

# Define a dense layer with 1 output node
predictions = tf.keras.layers.Dense(1, activation='sigmoid')(dense2)

# Print the shapes of dense1, dense2, and predictions
print(f'{dense1.shape=}')
print(f'{dense2.shape=}')
print(f'{predictions.shape=}')

dense1.shape=TensorShape([10, 7])
dense2.shape=TensorShape([10, 3])
predictions.shape=TensorShape([10, 1])


In [7]:
# Activation functions ¿Why?

# Define example borrower features
young, old = 0.3, 0.6
low_bill, high_bill = 0.1, 0.5

# Apply matrix multiplication step for all feature combinations
young_high = 1.0 * young + 2.0 * high_bill
young_low = 1.0 * young + 2.0 * low_bill
old_high = 1.0 * old + 2.0 * high_bill
old_low = 1.0 * old + 2.0 * low_bill

# Difference in default predictions for young
young_diff = young_high - young_low

# Difference in default predictions for old
old_diff = old_high - old_low

# Linear computations are not good enough to make predictions
print(young_diff == old_diff)  # not good

# Introduce nonlinearity
from tensorflow.keras.activations import sigmoid

# Difference in default predictions for young (non-linear)
young_diff_nl = sigmoid(young_high) - sigmoid(young_low)

# Difference in default predictions for old (non-linear)
old_diff_nl = sigmoid(old_high) - sigmoid(old_low)

# Non-linearities introduce good complexity into the model
print((young_diff_nl == old_diff_nl).numpy())  # good

True
False


In [8]:
from tensorflow.keras.layers import Dense

# Define input layer
inputs = tf.constant(borrower_features, tf.float32)

# Define dense layer 1
dense1 = Dense(16, activation='relu')(inputs)

# Define dense layer 2
dense2 = Dense(8, activation='sigmoid')(dense1)

# Define output layer
outputs = Dense(4, activation='softmax')(dense2)

In [9]:
# Untrained network

# Features
bill_amounts = np.array([[ 77479,  77057,  78102],
       [   326,    326,    326],
       [ 13686,   1992,    604],
       [336722, 276725, 260932],
       [231759, 233357, 236292],
       [  1825,   2017,   2476],
       [ 12136,   7938,    620],
       [ 36159,  38241,  39121],
       [205736, 199379, 132963],
       [   692,     -6,    890]])

# Target
default = np.array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0]])

# Construct imput layer from features
inputs = tf.constant(bill_amounts, tf.float32)

# Define first dense layer
dense1 = tf.keras.layers.Dense(3, activation='relu')(inputs)

# Define second dense layer
dense2 = tf.keras.layers.Dense(2, activation='relu')(dense1)

# Define output layer
outputs = tf.keras.layers.Dense(1, activation='sigmoid')(dense2)

# Print error for first five examples
error = default[:5] - outputs.numpy()[:5]
error

array([[-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.]])

In [10]:
# Multiclass classification problems

from tensorflow.keras.layers import Dense

# Features
borrower_features = np.array([[180201, 181443, 155045,  95145,  86025,   7000,   7000,   3100,
         92101,   3200],
       [ 12200,   8140,  10176,  20719,  15665,   1518,   5019,  15027,
           639,    547],
       [  1078,   5543,    500,    617,    617,   5562,    810,    617,
             0,      0],
       [  2422,    894,      0,      0,   1639,    894,      0,      0,
          1639,    923],
       [ 66380,  68083,  50822,  31179,  28686,   4000,   3012,   5000,
          2000,   3000],
       [   430,      0,  46257,  45975,   1300,      0,  46257,   2200,
          1300,  43987],
       [  1558,      0,    940,      0,    699,      0,    940,      0,
           699,      0],
       [150603, 153900,      0,      0,      0,   7000,      0,      0,
             0,      0],
       [    -5,    580,   2207,    630,    540,    585,   2207,    630,
           540,      0],
       [ 42372,  35580,  28330,  28136,  26752,   1500,   1800,   1088,
          1200,   1200]])


# Construct input layer from borrower features
inputs = tf.constant(borrower_features, tf.float32)

# Define first dense layer
dense1 = Dense(10, activation='sigmoid')(inputs)

# Define second dense layer
dense2 = Dense(8, activation='relu')(dense1)

# Define output layer
outputs = Dense(6, activation='softmax')(dense2)

# Print first five outputs
print(outputs.numpy()[:5])

# Print sum of all columns
tf.reduce_sum(outputs, 1).numpy()

[[0.1621499  0.16891964 0.17174156 0.16348976 0.17454083 0.15915838]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16460946 0.13786268 0.16842279 0.20009929 0.18186359 0.14714216]
 [0.15417656 0.17247207 0.1804868  0.15769449 0.188667   0.14650303]
 [0.16074038 0.16958669 0.17330706 0.1624823  0.17701629 0.15686728]]


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [17]:
tf.keras.layers.Dense(1)(borrower_features)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[111471.61   ],
       [ -2891.168  ],
       [  2115.7837 ],
       [ -1185.4141 ],
       [ 37566.15   ],
       [ 12176.676  ],
       [   165.06198],
       [ 35832.105  ],
       [  1601.697  ],
       [ 17244.33   ]], dtype=float32)>

In [23]:
default

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0]])

In [37]:
# Optimizers

from tensorflow.keras.activations import sigmoid
from tensorflow.keras.losses import binary_crossentropy
from tensorflow.keras.optimizers import RMSprop

bias = tf.Variable(tf.random.normal([1]))
weights = tf.Variable(tf.random.normal([1, 10]))

# Define the model function
def model(bias, weights, features=borrower_features):
  return tf.transpose(sigmoid(bias + weights @ features))


# Compute the predicted values and loss
def loss_function(bias, weights, targets=default, features=borrower_features):
  predictions = model(bias, weights, features)
  return binary_crossentropy(targets, predictions)


# Minimize the loss function with RMS propagation
opt = RMSprop(learning_rate=0.01, momentum=0.9)
for j in range(1000):
  opt.minimize(lambda: loss_function(bias, weights), var_list=[bias, weights])
  
  if not j % 100: print(loss_function(bias, weights).numpy())

[ 0.        0.        0.        0.        0.        0.        0.
  0.       15.424949 -0.      ]
[ 0.        0.        0.        0.        0.        0.        0.
  0.       15.424949 -0.      ]
[ 0.        0.        0.        0.        0.        0.        0.
  0.       15.424949 -0.      ]
[ 0.        0.        0.        0.        0.        0.        0.
  0.       15.424949 -0.      ]
[ 0.        0.        0.        0.        0.        0.        0.
  0.       15.424949 -0.      ]
[ 0.        0.        0.        0.        0.        0.        0.
  0.       15.424949 -0.      ]
[ 0.        0.        0.        0.        0.        0.        0.
  0.       15.424949 -0.      ]
[ 0.        0.        0.        0.        0.        0.        0.
  0.       15.424949 -0.      ]
[ 0.        0.        0.        0.        0.        0.        0.
  0.       15.424949 -0.      ]
[ 0.        0.        0.        0.        0.        0.        0.
  0.       15.424949 -0.      ]


In [ ]:
# The dangers of local minima

# Loss function with two local minima
def loss_function(x):
  return (abs(x) + 1) * abs(x - 7)

from tensorflow.keras.optimizers import SGD

# Initialize x_1 and x_2
x_1 = tf.Variable(6.0, tf.float32)
x_2 = tf.Variable(0.3, tf.float32)

# Define the optimization operation
opt = SGD(learning_rate=0.01)

# Perform minimization using the loss function and x_1
for j in range(100):
  opt.minimize(lambda: loss_function(x_1), var_list=[x_1])

# Perform minimization using the loss function and x_2
for j in range(100):
  opt.minimize(lambda: loss_function(x_2), var_list=[x_2])

# Compare x_1 and x_2
print(x_1.numpy(), x_2.numpy())

# Observe the loss function to understand why minimization results diverge
from matplotlib import pyplot as plt
xs = np.linspace(-1, 8)
plt.plot(xs, [loss_function(x) for x in xs])

In [ ]:
# Momentum avoids local minima

from tensorflow.keras.optimizers import RMSprop

# Initialize x_1 and x_2
x_1 = tf.Variable(-2.0, tf.float32)
x_2 = tf.Variable(-2.0, tf.float32)

# Define the optimization operation for opt_1 and opt_2
opt_1 = RMSprop(learning_rate=0.01, momentum=0.99)
opt_2 = RMSprop(learning_rate=0.01, momentum=0.00)

# Perform minimization using the loss function and x_1
for j in range(1000):
  opt_1.minimize(lambda: loss_function(x_1), var_list=[x_1])
  
# Perform minimization using the loss function and x_2
for j in range(1000):
  opt_2.minimize(lambda: loss_function(x_2), var_list=[x_2])

# Compare x_1 and x_2
print(x_1.numpy(), x_2.numpy())

In [41]:
# Initialization

# Define the layer 1 weights
w1 = tf.Variable(tf.random.normal([23, 7]))

# Initialize the layer 1 bias
b1 = tf.Variable(tf.ones([7]))

# Define the layer 2 weights
w2 = tf.Variable(tf.random.normal([7, 1]))

# Define the layer 2 bias
b2 = tf.Variable(0.0)

# Define the model
def model(w1, b1, w2, b2, features=borrower_features):
  # Apply relu activation functions to layer 1
  layer1 = tf.keras.activations.relu(tf.matmul(features, w1) + b1)
  # Apply dropout rate of 0.25
  dropout = tf.keras.layers.Dropout(0.25)(layer1)
  return tf.keras.activations.sigmoid(tf.matmul(dropout, w2) + b2)


# Define the loss function
def loss_function(w1, b1, w2, b2, features=borrower_features, targets=default):
  predictions = model(w1, b1, w2, b2)
  # Pass targets and predictions to the cross entropy loss
  return tf.keras.losses.binary_crossentropy(targets, predictions)