<a href="https://colab.research.google.com/github/PabloBrianese/introduction-to-deep-learning/blob/main/chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [3]:
# 0D Tensor
d0 = tf.ones((1,))

d0

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [5]:
# 1D Tensor
d1 = tf.ones((2,))
d1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [7]:
# 2D Tensor
d2 = tf.ones((2, 2))
d2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [9]:
# 3D Tensor
d3 = tf.ones((2, 2, 2))
d3

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [10]:
# Print the 3D Tensor
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [12]:
# Define a 2x3 constant
a = tf.constant(3, shape=[2, 3])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]], dtype=int32)>

In [13]:
# Define a 2x2 constant
b = tf.constant([1, 2, 3, 4], shape=[2, 2])
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [15]:
# Define a variable
a0 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.float32)
a0

<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [16]:
a1 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.int16)
a1

<tf.Variable 'Variable:0' shape=(6,) dtype=int16, numpy=array([1, 2, 3, 4, 5, 6], dtype=int16)>

In [18]:
# Define a constant
b = tf.constant(2, tf.float32)
b

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [19]:
# Compute their product
c0 = tf.multiply(a0, b)
c0

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 2.,  4.,  6.,  8., 10., 12.], dtype=float32)>

In [20]:
c1 = a0*b
c1

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 2.,  4.,  6.,  8., 10., 12.], dtype=float32)>