<a href="https://colab.research.google.com/github/PabloBrianese/introduction-to-deep-learning/blob/main/chapter2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

data_path = 'kc_house_data.csv'

housing = pd.read_csv(data_path)

housing.price

0        221900.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
           ...   
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: price, Length: 21613, dtype: float64

In [4]:
import numpy as np
import tensorflow as tf

# Use a numpy array to define price as a 32-bit float
price = np.array(housing.price, np.float32)

# Define waterfront as a Boolean using cast
waterfront = tf.cast(housing.waterfront, tf.bool)

print(price); print(waterfront)

[221900. 538000. 180000. ... 402101. 400000. 325000.]
tf.Tensor([False False False ... False False False], shape=(21613,), dtype=bool)


In [7]:
# Compute the MSE loss
targets = [1, 2]
predictions = [1.1, 2.1]
loss = tf.keras .losses.mse(targets, predictions)
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.009999992>

In [8]:
# Define a a linear regression model
def linear_regression(intercept, slope, features):
  return intercept + features * slope


# Define a loss function to compute the MSE
def loss_function(intercept, slope, targets, features):
  # Compute the predictions for a linear model
  predictions = linear_regression(intercept, slope, features)

  # Compute the MSE loss
  loss = tf.keras.losses.mse(targets, predictions)
  
  return loss


intercept = 0
slope = 1
targets = np.ones([5])
features = np.zeros([5])

loss_function(intercept, slope, targets, features)

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [14]:
# Tensor of house prices
price = np.array([ 221900.,  538000.,  180000.,  604000.,  510000., 1225000.,
        257500.,  291850.,  229500.,  323000.], dtype=np.float32)

# Tensor of predicted house prices
predictions = np.array([154546.51228417, 153942.9622033 ,  40833.26164156, 332994.12052607,
       366929.17459064, 518305.41365246, 252546.78108404, 199867.55920599,
       110373.87139066, 126653.95837671])

# Import the keras module from tensorflow
from tensorflow import keras

# Compute the mean squared error (mse)
mse = keras.losses.mse(price, predictions)

print(mse.numpy())

# Compute the mean absolute error (mae)
mae = keras.losses.mae(price, predictions)

print(mae.numpy())

82596247419.03
212375.63850444002


In [15]:
features = tf.constant([1., 2., 3., 4., 5.], dtype=tf.float32)
targets = tf.constant([ 2.,  4.,  6.,  8., 10.], dtype=tf.float32)

# Initialize a variable named scalar
scalar = tf.Variable(1.0, dtype=tf.float32)


# Define the model
def model(scalar, features=features):
  return scalar * features


# Define a loss function
def loss_function(scalar, features=features, targets=targets):
  # Compute the predicted values
  predictions = model(scalar, features)

  # Return the mean absolute error loss
  return keras.losses.mae(targets, predictions)


# Evaluate the loss function and print the loss
loss_function(scalar).numpy()

3.0

In [22]:
# Define the targets and features
price = np.array(housing.price, np.float32)
size = np.array(housing.sqft_living, np.float32)

# Define the intercept and slope, as trainable Variables
intercept = tf.Variable(0.1, np.float32)
slope = tf.Variable(0.1, np.float32)
var_list = [intercept, slope]


# Define a linear regression model
def linear_regression(intercept, slope, features=size):
  return intercept + features * slope


# Compute the predicted values and loss
def loss_function(intercept, slope, targets=price, features=size):
  predictions = linear_regression(intercept, slope)
  return tf.keras.losses.mse(targets, predictions)


# Define an optimization operation
opt = tf.keras.optimizers.Adam()

# Minimize the loss function and print the loss
for j in range(10000):
  opt.minimize(lambda: loss_function(*var_list), var_list=var_list)
  if not j % 1000: print(loss_function(*var_list))


print(intercept.numpy(), slope.numpy())

tf.Tensor(426196570000.0, shape=(), dtype=float32)
tf.Tensor(423483800000.0, shape=(), dtype=float32)
tf.Tensor(420784930000.0, shape=(), dtype=float32)
tf.Tensor(418098580000.0, shape=(), dtype=float32)
tf.Tensor(415423560000.0, shape=(), dtype=float32)
tf.Tensor(412759430000.0, shape=(), dtype=float32)
tf.Tensor(410106400000.0, shape=(), dtype=float32)
tf.Tensor(407463700000.0, shape=(), dtype=float32)
tf.Tensor(404831100000.0, shape=(), dtype=float32)
tf.Tensor(402207700000.0, shape=(), dtype=float32)
10.066566 10.068806
